services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - PORT=4000
      - CORS_ORIGIN=http://localhost:80
    healthcheck:
      test:
        ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:4000/api/health']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:4000/api
      - VITE_SOCKET_HOST=ws://localhost:4000
      - VITE_SOCKET_PATH=/stream
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: maritime-network
    driver: bridge
